version: "3.3"
volumes:
  my-volume:
    external: false
networks:
  mt-network:
    driver: bridge    
services:
  mydb:
    image: mysql
    container_name: miniproj_db
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined  
    networks:
      - mt-network      
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=miniproj
    volumes:
      - my-volume:/var/lib/mysql
  backend:
    build: .
    container_name: miniproj_back
    ports:
      - 8090:8090  
    networks:
      - mt-network
    environment:
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=
      - SPRING_DATASOURCE_URL=jdbc:mysql://mydb:3306/miniproj
      - MYSQL_DATABASE=miniproj   
    depends_on:
      - mydb 
